version: 2

updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 0
      labels:
          - 'scope/ci-cd'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 0
      labels:
          - 'scope/ci-cd'
