import Link from 'next/link'
import { ArrowRight, CheckCircle2 } from 'lucide-react'

import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

export function PipelineStagesSection() {
    return (
        <section className="space-y-6">
            <div>
                <h2 className="mb-3 text-2xl font-bold">The Data Pipeline</h2>
                <p>
                    SynthArena processes predictions through a structured, four-stage pipeline that ensures
                    reproducibility and traceability.
                </p>
            </div>

            <div className="space-y-4">
                <Card variant="bordered">
                    <CardContent className="px-6 py-4">
                        <div className="flex items-center gap-3 overflow-x-auto">
                            <div className="shrink-0">
                                <div className="bg-background rounded-lg border p-4 text-center">
                                    <div className="font-mono text-xs font-semibold">1. Raw</div>
                                </div>
                            </div>
                            <ArrowRight className="text-muted-foreground size-5 shrink-0" />
                            <div className="shrink-0">
                                <div className="bg-background rounded-lg border p-4 text-center">
                                    <div className="font-mono text-xs font-semibold">2. Processed</div>
                                </div>
                            </div>
                            <ArrowRight className="text-muted-foreground size-5 shrink-0" />
                            <div className="shrink-0">
                                <div className="bg-background rounded-lg border p-4 text-center">
                                    <div className="font-mono text-xs font-semibold">3. Scored</div>
                                </div>
                            </div>
                            <ArrowRight className="text-muted-foreground size-5 shrink-0" />
                            <div className="shrink-0">
                                <div className="bg-background rounded-lg border p-4 text-center">
                                    <div className="font-mono text-xs font-semibold">4. Results</div>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="space-y-6">
                <Card variant="bordered">
                    <CardContent className="space-y-3 px-6 py-4">
                        <p>
                            <strong>1. Raw Data:</strong> Model predictions in their native output format. This stage is
                            immutable—files are never modified after generation.
                        </p>
                        <div className="bg-muted/50 rounded-lg p-4">
                            <div className="font-mono text-xs">
                                data/2-raw/<span className="text-blue-600 dark:text-blue-400">&lt;model&gt;</span>/
                                <span className="text-green-600 dark:text-green-400">&lt;benchmark&gt;</span>
                                /predictions.json.gz
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card variant="bordered">
                    <CardContent className="space-y-3 px-6 py-4">
                        <p>
                            <strong>2. Processed Data:</strong> Standardized Route objects generated by running the
                            adapter. This stage performs canonicalization, deduplication, and optional sampling.
                        </p>
                        <div className="bg-muted/50 rounded-lg p-4">
                            <div className="font-mono text-xs">
                                data/3-processed/<span className="text-blue-600 dark:text-blue-400">&lt;model&gt;</span>
                                /<span className="text-green-600 dark:text-green-400">&lt;benchmark&gt;</span>
                                /candidates.json.gz
                            </div>
                        </div>
                        <div className="space-y-2">
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">SMILES canonicalization ensures consistency</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">Duplicate routes removed using cryptographic signatures</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">Optional top-k sampling limits routes per target</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card variant="bordered">
                    <CardContent className="space-y-3 px-6 py-4">
                        <p>
                            <strong>3. Evaluation Bundle:</strong> Every ranked candidate retains independent Tier-0
                            syntax, task-constraint, and acceptable-route evidence.
                        </p>
                        <div className="bg-muted/50 rounded-lg p-4">
                            <div className="font-mono text-xs">
                                evaluation.json.gz + analysis.json.gz + manifest.json
                            </div>
                        </div>
                        <div className="space-y-2">
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">
                                    <code className="bg-muted rounded px-1 text-xs">Tier-0</code>: Molecular graphs and
                                    reaction records are syntactically well formed
                                </p>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">
                                    <code className="bg-muted rounded px-1 text-xs">Solv-0[stock]</code>: A Tier-0-pass
                                    candidate also satisfies the named stock constraint
                                </p>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">Structural properties (length, convergence) computed</p>
                            </div>
                        </div>
                        <Alert>
                            <AlertDescription>
                                Tier-0 and Solv-0 do not claim reaction-topology validity or chemical feasibility; those
                                require higher-tier evidence.
                            </AlertDescription>
                        </Alert>
                    </CardContent>
                </Card>

                <Card variant="bordered">
                    <CardContent className="space-y-3 px-6 py-4">
                        <p>
                            <strong>4. Results:</strong> Aggregate statistics with confidence intervals. This is what
                            you see on the leaderboard.
                        </p>
                        <div className="bg-muted/50 rounded-lg p-4">
                            <div className="font-mono text-xs">
                                data/5-results/
                                <span className="text-green-600 dark:text-green-400">&lt;benchmark&gt;</span>/
                                <span className="text-blue-600 dark:text-blue-400">&lt;model&gt;</span>/report.md
                            </div>
                        </div>
                        <div className="space-y-2">
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">Target-level Tier-0 and Solv-0[stock] rates with 95% CI</p>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">
                                    Top-K accuracy (K ∈ {'{'}1, 3, 5, 10, ...{'}'})
                                </p>
                            </div>
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="size-4 shrink-0 text-green-600 dark:text-green-400" />
                                <p className="text-sm">Stratified performance by route length and topology</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="space-y-4">
                <p>
                    <strong>Reproducibility & Verification:</strong> Every file generated by the pipeline has a
                    companion manifest that records SHA256 hashes of input/output files, command parameters, timestamp,
                    and software version.
                </p>
            </div>

            <div className="border-t pt-6">
                <div className="flex flex-wrap gap-3">
                    <Link href="/thesis">
                        <Button variant="outline">
                            Read Motivation for the Project
                            <ArrowRight className="ml-2 size-4" />
                        </Button>
                    </Link>
                    <a href="https://retrocast.ischemist.com/concepts" target="_blank" rel="noopener noreferrer">
                        <Button variant="outline">
                            RetroCast Technical Docs
                            <ArrowRight className="ml-2 size-4" />
                        </Button>
                    </a>
                </div>
            </div>
        </section>
    )
}
