import Link from 'next/link'
import { format, formatDistanceToNow } from 'date-fns'
import { Check, Clock, Coins, Zap } from 'lucide-react'

import type { RunTitleCardData } from '@/lib/services/view/prediction.view'
import { SubmissionBadge } from '@/components/badges/submission'
import { Separator } from '@/components/ui/separator'

type RunTitleCardProps = {
    dataPromise: Promise<RunTitleCardData>
}

type StatBlockProps = {
    icon: React.ElementType
    value: string
    label: string
    tooltip: string
}

function StatBlock({ icon: Icon, value, label, tooltip }: StatBlockProps) {
    return (
        <div className="flex items-center gap-4" title={tooltip}>
            <div className="flex size-10 items-center justify-center rounded-lg bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400">
                <Icon className="size-5" />
            </div>
            <div>
                <div className="text-lg font-semibold">{value}</div>
                <div className="text-muted-foreground text-xs">{label}</div>
            </div>
        </div>
    )
}

export async function RunTitleCard({ dataPromise }: RunTitleCardProps) {
    const run = await dataPromise

    return (
        <div className="bg-card text-card-foreground rounded-lg border">
            <div className="flex flex-col items-start gap-4 p-6 sm:flex-row sm:items-center sm:justify-between">
                <div className="grid gap-1">
                    <h1 className="text-2xl font-bold tracking-tight">
                        <Link
                            href={`/model-families/${run.modelFamilySlug}`}
                            className="hover:text-primary transition-colors"
                        >
                            {run.modelFamilyName}
                        </Link>
                        <span className="text-muted-foreground mx-2 font-normal">on</span>
                        <Link href={`/benchmarks/${run.benchmarkId}`} className="hover:text-primary transition-colors">
                            {run.benchmarkName}
                        </Link>
                    </h1>
                    <div className="text-muted-foreground text-sm">
                        Part of the{' '}
                        <Link
                            href={`/algorithms/${run.algorithmSlug}`}
                            className="text-foreground font-medium hover:underline"
                        >
                            {run.algorithmName}
                        </Link>{' '}
                        algorithm family
                    </div>
                </div>
                <div className="shrink-0">
                    <SubmissionBadge
                        submissionType={run.submissionType}
                        isRetrained={run.isRetrained}
                        badgeStyle="soft"
                    />
                </div>
            </div>
            <Separator />
            <div className="grid grid-cols-2 gap-x-6 gap-y-4 p-6 sm:grid-cols-2 md:grid-cols-3 lg:flex lg:items-center lg:justify-between">
                <StatBlock
                    icon={Zap}
                    value={run.totalRoutes.toLocaleString()}
                    label="Routes Found"
                    tooltip="Total unique routes generated by the model for this benchmark."
                />
                <StatBlock
                    icon={Clock}
                    value={run.totalWallTime ? `${(run.totalWallTime / 60).toFixed(1)} min` : 'N/A'}
                    label="Total Duration"
                    tooltip="Total wall clock time for the prediction run."
                />
                <StatBlock
                    icon={Coins}
                    value={run.totalCost != null ? `$${run.totalCost.toFixed(2)}` : 'N/A'}
                    label="Cost"
                    tooltip="Computational cost for the run."
                />
                <StatBlock
                    icon={Check}
                    value={format(new Date(run.executedAt), 'MMM d, yyyy')}
                    label="Executed"
                    tooltip={`Executed ${formatDistanceToNow(new Date(run.executedAt), { addSuffix: true })}`}
                />
            </div>
        </div>
    )
}
